### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Apoliak7777** [xxcosita3czxx/Lorelei-bot#9]
Make a giveways bot based on /giveway and create a contest

Add a ticket rating setting

**Comment by xxcosita3czxx** [comment]
Okay

**Comment by xxcosita3czxx** [comment]
User profile done in context menu, you right click user and Apps. Tell me if you want also command

**Comment by xxcosita3czxx** [comment]
Ticket rating done

**Comment by Apoliak7777** [comment]
c
